const QUERY_KEYS = {
  // requests
  GET_NOT_OPENED_REQUESTS_COUNT: "GET_NOT_OPENED_REQUESTS_COUNT",
  LIST_REQUESTS: "LIST_REQUESTS",
  UPDATE_REQUEST_STATUS: "UPDATE_REQUEST_STATUS",
  DELETE_REQUEST: "DELETE_REQUEST",
};

export default QUERY_KEYS;
