const QUERY_KEYS = {
  // requests
  GET_NOT_OPENED_REQUESTS_COUNT: "GET_NOT_OPENED_REQUESTS_COUNT",
  LIST_REQUESTS: "LIST_REQUESTS",
  UPDATE_REQUEST_STATUS: "UPDATE_REQUEST_STATUS",
  DELETE_REQUEST: "DELETE_REQUEST",

  // customers
  LIST_CUSTOMERS: "LIST_CUSTOMERS",
  GET_CUSTOMER: "GET_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",
  GET_CUSTOMER_USAGE: "GET_CUSTOMER_USAGE",
  GET_CUSTOMER_KEYS: "GET_CUSTOMER_KEYS",
  GET_CUSTOMER_PROVIDERS: "GET_CUSTOMER_PROVIDERS",
  GET_CUSTOMER_MESSAGES: "GET_CUSTOMER_MESSAGES",

  // auth
  GET_PROFILE: "GET_PROFILE",
  
  // license keys
  LIST_LICENSE_KEYS: "LIST_LICENSE_KEYS",
  CREATE_LICENSE_KEY: "CREATE_LICENSE_KEY",
  DELETE_LICENSE_KEY: "DELETE_LICENSE_KEY",
};

export default QUERY_KEYS;
